### PR TITLE
Fix "undefined method `blank?'"

### PR DESCRIPTION
**Pull request by astencel-sumo**
When running the `samples/file-input-example` on `docker.elastic.co/logstash/logstash-oss:7.9.3` image, I'm getting the following errors:
```console
2020-12-18 09:45:24.622 ERROR [[main]>worker1] [logstash.outputs.sumologic] error when processing event {:event=>#<LogStash::Event:0x229cafd>, :message=>"undefined method `blank?' for \"Logstash\":String", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/header_builder.rb:28:in `build'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/piler.rb:60:in `input'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:141:in `receive'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `block in multi_receive'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:138:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:295:in `block in start_workers'"]}
2020-12-18 09:45:24.622 ERROR [[main]>worker2] [logstash.outputs.sumologic] error when processing event {:event=>#<LogStash::Event:0x74ee4c9b>, :message=>"undefined method `blank?' for \"Logstash\":String", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/header_builder.rb:28:in `build'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/piler.rb:60:in `input'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:141:in `receive'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `block in multi_receive'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:138:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:295:in `block in start_workers'"]}
2020-12-18 09:45:24.623 ERROR [[main]>worker6] [logstash.outputs.sumologic] error when processing event {:event=>#<LogStash::Event:0x26c59e92>, :message=>"undefined method `blank?' for \"Logstash\":String", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/header_builder.rb:28:in `build'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic/piler.rb:60:in `input'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:141:in `receive'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `block in multi_receive'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/vendor/local_gems/ba86d2b9/logstash-output-sumologic-1.3.0/lib/logstash/outputs/sumologic.rb:136:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:138:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:295:in `block in start_workers'"]}
```

This code seems to work fine in Logstash 6.8.9.

Logstash 7 has a [LogStash::Util.blank?](https://github.com/elastic/logstash/blob/d176e608bdd20a3221bdbb8b3fc84fc3f1085229/logstash-core/lib/logstash/util.rb#L228) method which we could use, but it is unavailable in Logstash 6, so using it would restrict this plugin's usage to only Logstash 7 and above. To be able to support Logstash 6, I replicated the `LogStash::Util.blank?` method in this plugin as `LogStash::Output::Sumologic::Common.blank?`.

### CODE REVIEW

**Review by perk-sumo — APPROVED** [review]

File: lib/logstash/outputs/sumologic/common.rb [hunk 1]
```diff
@@ -69,5 +69,15 @@ def log_dbg(message, *opts)
       end
     end # def log_dbg
 
+    def blank?(value)
+      if value.kind_of?(NilClass)
+        true
+      elsif value.kind_of?(String)
+        value !~ /\S/
```
Comment (sumo-drosiek) [inline lib/logstash/outputs/sumologic/common.rb:76]: Is it faster than `value.strip().length == 0`? Just curious

Comment (astencel-sumo) [reply lib/logstash/outputs/sumologic/common.rb:76]: I didn't go into details, just copied over from LogStash original method https://github.com/elastic/logstash/blob/d176e608bdd20a3221bdbb8b3fc84fc3f1085229/logstash-core/lib/logstash/util.rb#L228
